import dotenv from 'dotenv';
dotenv.config();

const MONGO_URI = process.env.MONGO_URI;
const JWT_SECRET = process.env.JWT_SECRET;
const PORT = process.env.PORT;
const AUTH_TOKEN_EXP_DAY  = process.env.AUTH_TOKEN_EXP_DAY
const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY
const CLOUDINARY_CLOUD_NAME= process.env.CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_API_KEY= process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET= process.env.CLOUDINARY_API_SECRET;
let ADMIN_NAME = process.env.ADMIN_NAME;
ADMIN_NAME = ADMIN_NAME.split('_');
ADMIN_NAME = ADMIN_NAME[0] + " " + ADMIN_NAME[1];
const ADMIN_EMAIL = process.env.ADMIN_EMAIL;
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD;
const ADMIN_ROLE = process.env.ADMIN_ROLE;
const UDEMY_CLIENT_SECRET=process.env.UDEMY_CLIENT_SECRET;
const UDEMY_CLIENT_ID=process.env.UDEMY_CLIENT_ID;
const UDEMY_BASE_URL=process.env.UDEMY_BASE_URL;
export default { MONGO_URI, JWT_SECRET , PORT,AUTH_TOKEN_EXP_DAY,STRIPE_SECRET_KEY,CLOUDINARY_CLOUD_NAME,CLOUDINARY_API_KEY,CLOUDINARY_API_SECRET,
    ADMIN_EMAIL,ADMIN_NAME,ADMIN_PASSWORD,ADMIN_ROLE,UDEMY_BASE_URL,UDEMY_CLIENT_ID,UDEMY_CLIENT_SECRET
};
